[imap]
server = "imap.gmail.com"
port = 993
username = "${IMAP_USERNAME}"
password = "${IMAP_PASSWORD}"
use-ssl = true
check-interval-seconds = 30

[[monitor]]
mailbox = "smart/Notification"

[[monitor.triggers]]
regex-pattern = "Your Relish order from .* is here"
command = "/home/dancer/actions/lunch-arrived"

[[monitor.triggers]]
regex-pattern = "Your Relish delivery from .* is running late."
command = "/home/dancer/actions/lunch-late"

[[monitor.triggers]]
regex-pattern = "We see your order is running late. Sorry for the delay on your Relish order"
command = "/home/dancer/actions/lunch-late"
