[imap]
server = "imap.gmail.com"
port = 993
username = "${IMAP_USERNAME}"
password = "${IMAP_PASSWORD}"
use-ssl = true
check-interval-seconds = 30

[[monitor]]
mailbox = "smart/Notification"

[[monitor.triggers]]
regex-pattern = "Your Relish order from .* is here"
command = "/home/dancer/bin/dancerctl on left0 --duration 10"
